### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ladyloki1694** [sparkfun/Pokedex#12]
I would love one of those for my Nexus 6p but I don't know how to do any of it. How much would it cost for you to do one?

**Comment by ladyloki1694** [comment]
I'm also Team Mystics. It would be nice if you could put that on the front of the case

**Comment by darknessblade** [comment]
it mostly depends on where you live (shipping cost)
and the resolution of the print,
the material cost (high quality, so no ebay) (print material)

## *features, powered fan, pokemon go+ build in, powerbank, other

if someone where to print it for you (so print only) it could cost up to 10-20$
adding in the features: a price of 50$ minimum would be a good point to start.

---

if you know someone who owns a 3d printer the print would cost (around 5$) (material cost)
(using low quality ebay items for features) (about 25$).

since mass production is cheaper, a reasonable price, if it was a real market item would be about 30-40$

**Comment by btc053013** [comment]
Well all I want is the cases.  I have a couple powerbanks I can install
myself.  I will pay shipping and the costs of the cases but was wondering
if you could make me one for the Samsung galaxy grand prime and one for the
Samsung galaxy Express 3

**Comment by darknessblade** [comment]
hello BTC

---

 (i dont have a printer myself, but i know someone who does, so i might be unable to give you a good price )
i will ask how much it would cost to print

---

as for shippping cost:
if you can provide me with your mail, and hometown 
i can look into how much it would cost to print it for you,

---

since i have to alter the model to fit your phones:

(if you can also provide me with pictures of your powerbank, i can look into it to fully imply the powerbank) (altering the model) (this only works with small bar/cilinder powerbanks)

**Comment by darknessblade** [comment]
hello BTC

------------------------------------------------------------------
 (i dont have a printer myself, but i know someone who does, so i might be unable to give you a good price )
i will ask how much it would cost to print
-------------------------------------------------------------------
as for shippping cost:
if you can provide me with your mail, and hometown 
i can look into how much it would cost to print it for you,
------------------------------------------------------------------
since i have to alter the model to fit your phones:

(if you can also provide me with pictures of your powerbank, i can look into it to fully imply the powerbank) (altering the model) (this only works with small bar/cilinder powerbanks)

**Comment by btc053013** [comment]
Darknessblade can you email me privately and I'll give you all that

**Comment by darknessblade** [comment]
btc, i made my  mail publoc for a short while please check in the next 2 hours, then i set it at privat again

**Comment by bboyho** [comment]
Hi,

I happened to come across this issue when checking out this repository. Sorry for the delay in reply. The project files were released to the public for those interested in adjusting the models and making their own case. There are no plans with SparkFun to adjust the files or selling the case as a product for the Nexus 6p. However, it looks like someone in the community tried making a universal body design [ [https://github.com/sparkfun/Pokedex/issues/8](https://github.com/sparkfun/Pokedex/issues/8) ] after [forking this repository](https://github.com/sparkfun/Pokedex/network/members). 

To modify, you will need a 3D modeling program (like Fusion 360, Tinkercad). If you do not have experience modifying 3D models, you may want to check out this tutorial on [Getting Started with 3D Printing Using Tinkercad](https://learn.sparkfun.com/tutorials/getting-started-with-3d-printing-using-tinkercad/) for an idea on how to design and print an enclosure. You'll need a [3D printer](https://www.sparkfun.com/categories/365) to print the models. If you don't have one, try checking a local maker space. 

It looks like user "darknessblade" might have been able to help you out. =)
